- name: Automated deploy EC2 webserver
  hosts: localhost
  connection: local
  gather_facts: False

  vars:
    instance_type: t2.micro
    image: ami-090fa75af13c156b4
    count: 1
    tag_value: qrious-test

  tasks:
  - name: Install prerequisites libs and modules
    become: yes
    pip:
      name:
        - boto3
        - boto
      state: present
    register: check_install

  - debug: msg="{{ check_install.stdout_lines }}"

  - name: Create new VPC for webserver
    ec2_vpc_net:
      name: qrious-vpc1
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      cidr_block: 10.10.0.0/16
      region: "{{ aws_region }}"
      tenancy: default
      state: present
      tags:
        Group: "{{ tag_value }}"
    register: vpc_data

  - set_fact:
      new_vpc_id: "{{ vpc_data.vpc.id }}"

  - debug: msg="{{ vpc_data }}"

  - name: Create new subnet for qrious VPC
    ec2_vpc_subnet:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      vpc_id: "{{ new_vpc_id }}"
      region: "{{ aws_region }}"
      state: present
      cidr: 10.10.1.0/24
      map_public: yes
      tags:
        Name: qrious-subnet1-pub
    register: subnet1_data

  - debug: msg="{{ vpc_data }}"

  - name: Create new internet gateway for qrious VPC
    ec2_vpc_igw:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      vpc_id: "{{ new_vpc_id }}"
      region: "{{ aws_region }}"
      state: "present"
      tags:
        Name: qrious-igw1
    register: igw1_date
